[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  VITE_SUPABASE_URL = "https://fvlstvvvwrtmuujxwxml.supabase.co"
  VITE_SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZ2bHN0dnZ2d3J0bXV1anh3eG1sIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTkxNjg5ODMsImV4cCI6MjA3NDc0NDk4M30.JzI45Ay51RtsEJMMJjh9SrftWQQVeOCMVF9z9jqowdw"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
